language: python
python:
  - "3.4"
  - "3.5"
script: make test
notifications:
  email: false
addons:
  postgresql: "9.5"
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/surveys'
  matrix:
    - DJANGO='django~=1.9'
    - DJANGO='django~=1.10'
install:
  - psql -c 'CREATE DATABASE surveys' -U postgres;
  - pip install -r requirements.txt --use-wheel
  - pip install $DJANGO --use-wheel
