language: python
python:
  - "3.4"
  - "3.5"
notifications:
  email: false
addons:
  postgresql: "9.4"
  firefox: "47.0"
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/surveys'
  matrix:
    - DJANGO='django~=1.9.0'
before_install:
  - nvm install 6.3.1
  - nvm use 6.3.1
  - node --version
  - npm --version
install:
  - psql -c 'CREATE DATABASE surveys' -U postgres;
  - pip install -r requirements.txt --use-wheel
  - pip install $DJANGO --use-wheel
  - cd web && npm install && cd ..
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: make test
